services:
  _defaults:
    autowire: true

  O3\TinyMCE\Application\Core\TinyMCE\Loader:
    public: true
    arguments:
      $config: '@d3.tinymce.oxid.config'
      $language: '@d3.tinymce.oxid.language'

  O3\TinyMCE\Application\Core\TinyMCE\Configuration:
    arguments:
      $options: !tagged_iterator d3tinymce.option

  d3.tinymce.oxid.language:
    class: OxidEsales\Eshop\Core\Language
    factory: ['OxidEsales\Eshop\Core\Registry', 'getLang']

  d3.tinymce.oxid.config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', 'getConfig']

  O3\TinyMCE\Application\Core\TinyMCE\Options\Setup:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\BaseUrl:
    arguments:
      $config: '@d3.tinymce.oxid.config'
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\CacheSuffix:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Selector:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\InitInstanceCallback:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\LicenseKey:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Skin:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Promotion:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ContextMenu:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\MinHeight:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\MaxHeight:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Menubar:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ToolbarSticky:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ToolbarMode:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Resize:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ContentCss:
    arguments:
      $config: '@d3.tinymce.oxid.config'
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\EntityEncoding:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Protect:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\RemoveScriptHost:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ValidElements:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Language:
    arguments:
      $language: '@d3.tinymce.oxid.language'
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\LanguageUrl:
    arguments:
      $config: '@d3.tinymce.oxid.config'
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\DocumentBaseUrl:
    arguments:
      $config: '@d3.tinymce.oxid.config'
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\RelativeUrls:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ImageAdvtab:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Plugins:
    arguments:
      $plugins: !tagged_iterator d3tinymce.plugin
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\ExternalPlugins:
    arguments:
      $plugins: !tagged_iterator d3tinymce.plugin
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\FilemanagerUrl:
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\QuickbarsInsertToolbar:
    arguments:
      $plugins: !tagged_iterator d3tinymce.plugin
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Options\Toolbar:
    arguments:
      $toolbars: !tagged_iterator d3tinymce.toolbar
      $plugins: !tagged_iterator d3tinymce.plugin
    tags:
      - { name: d3tinymce.option, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Anchor:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Autolink:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\AutoResize:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Charmap:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Code:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\FullPage:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Image:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Legacyoutput:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Link:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Lists:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Media:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Nonbreaking:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Pagebreak:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Preview:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Quickbars:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\SearchReplace:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Table:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Visualblocks:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\WordCount:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\FullScreen:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Plugins\Roxy:
    tags:
      - { name: d3tinymce.plugin, default_priority_method: getPriority }

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Blocks:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Font:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Color:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Align:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Lists:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Indent:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\Blockquote:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}

  O3\TinyMCE\Application\Core\TinyMCE\Toolbar\RemoveFormat:
    tags:
      - { name: d3tinymce.toolbar, default_priority_method: getPriority}